name: CI/CD Pipeline

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'   

    - name: Restore dependencies
      run: dotnet restore

    - name: Run tests
      run: dotnet test --configuration Release --no-restore --verbosity normal

    - name: Build and publish
      run: dotnet publish -c Release -o ./publish

    - name: Deploy to Azure App Service
      if: success() && github.ref == 'refs/heads/main' 
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'azure-app'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './publish'
